{pkgs, ...}: {
  config.runtimePkgs = with pkgs; [
    universal-ctags
    ripgrep
    fd
    tree-sitter
    vscode-langservers-extracted
    yaml-language-server
    taplo
    bash-language-server
    shellcheck
    shfmt
    nodejs
    imagemagick
    actionlint
    cspell
    nixd
    nixfmt
    lua-language-server
    stylua
    templ
    lazygit
    gopls
    gotools
    go-tools
    basedpyright
    terraform-ls
    tflint
    tflint-plugins.tflint-ruleset-aws
    tflint-plugins.tflint-ruleset-google
    typescript
    typescript-language-server
    typescript-go
    vtsls
    eslint
    tailwindcss-language-server
    biome
    roslyn-ls
    netcoredbg
    docker-compose-language-service
    dockerfile-language-server
    hadolint
    alejandra
    csharpier
    prettierd
    sqlfluff
  ];
}
